// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/gorilla/mux"
	"go.uber.org/zap"
	"nvide-live/internal/delivery"
	"nvide-live/internal/domain"
	"nvide-live/internal/middleware"
	"nvide-live/internal/repository"
	"nvide-live/internal/usecase"
	"nvide-live/internal/webrtc"
	"nvide-live/internal/websocket"
	"nvide-live/internal/worker"
	"nvide-live/pkg/config"
	"nvide-live/pkg/database"
	"nvide-live/pkg/rbac"
	"nvide-live/pkg/redis"
	"nvide-live/pkg/wallet"
	worker2 "nvide-live/pkg/worker"
)

// Injectors from wire.go:

// InitializeApp configures the main dependency graph.
func InitializeApp(logger *zap.Logger) (*AppContainer, error) {
	config := ConfigProvider()
	db, err := DatabaseProvider(config, logger)
	if err != nil {
		return nil, err
	}
	client, err := RedisProvider(config, logger)
	if err != nil {
		return nil, err
	}
	pool := PgxPoolProvider(db)
	userRepository := repository.NewUserRepository(pool, logger)
	tokenRepository := repository.NewTokenRepository(pool, logger)
	roleRepository := repository.NewRoleRepository(pool, logger)
	service := AuthServiceProvider(config)
	manager := RbacManagerProvider(pool, logger)
	authUseCase := AuthUseCaseProvider(userRepository, tokenRepository, roleRepository, service, client, manager, logger, config)
	userUseCase := usecase.NewUserUseCase(userRepository, client, logger)
	storyRepository := repository.NewStoryRepository(pool, logger)
	storyViewRepository := repository.NewStoryViewRepository(pool, logger)
	storyUseCase := usecase.NewStoryUseCase(storyRepository, storyViewRepository, userRepository, logger)
	commentRepository := repository.NewCommentRepository(pool, logger)
	commentLikeRepository := repository.NewCommentLikeRepository(pool, logger)
	commentUseCase := usecase.NewCommentUseCase(commentRepository, commentLikeRepository, userRepository, logger)
	likeRepository := repository.NewLikeRepository(pool, logger)
	broker := BrokerProvider(client, logger)
	likeUseCase := usecase.NewLikeUseCase(likeRepository, client, broker, logger)
	messageRepository := repository.NewMessageRepository(pool, logger)
	chatRoomRepository := repository.NewChatRoomRepository(pool, logger)
	messageUseCase := usecase.NewMessageUseCase(messageRepository, chatRoomRepository, userRepository, logger)
	privateChatRepository := repository.NewPrivateChatRepository(pool, logger)
	privateChatUsecase := usecase.NewPrivateChatUsecase(privateChatRepository, userRepository, client, logger)
	paidInteractionRepository := repository.NewPaidInteractionRepository(pool, logger)
	walletRepository := repository.NewWalletRepository(pool, logger)
	transactionRepository := repository.NewTransactionRepository(pool, logger)
	agencyRepository := repository.NewAgencyRepository(pool, logger)
	paidInteractionUsecase := usecase.NewPaidInteractionUsecase(paidInteractionRepository, walletRepository, transactionRepository, userRepository, agencyRepository, client, logger)
	bookingRepository := repository.NewBookingRepository(pool, logger)
	withdrawalRepository := repository.NewWithdrawalRepository(pool, logger)
	payoutMethodRepository := repository.NewPayoutMethodRepository(pool, logger)
	cryptoPayoutAddressRepository := repository.NewCryptoPayoutAddressRepository(pool, logger)
	v := CryptoEncryptionKeyProvider(config)
	bool2 := MicroDepositVerifyEnabledProvider(config)
	payoutUsecase := usecase.NewPayoutUsecase(payoutMethodRepository, cryptoPayoutAddressRepository, v, bool2, logger)
	withdrawalUsecase := usecase.NewWithdrawalUsecase(withdrawalRepository, walletRepository, transactionRepository, agencyRepository, userRepository, payoutUsecase, client, logger)
	bookingUsecase := usecase.NewBookingUsecase(bookingRepository, walletRepository, agencyRepository, withdrawalUsecase, client, logger)
	offerRepository := repository.NewOfferRepository(pool, logger)
	offerUsecase := usecase.NewOfferUsecase(offerRepository, bookingRepository, bookingUsecase, walletRepository, agencyRepository, client, logger)
	locationUsecase := usecase.NewLocationUsecase(bookingRepository, client, logger)
	liveScheduleRepository := repository.NewLiveScheduleRepository(pool, logger)
	waitRoomHub := websocket.NewWaitRoomHub(pool, client, logger)
	hub := websocket.NewHub(pool, broker, client, logger)
	v2 := WaitRoomHubInterfaceProvider(waitRoomHub)
	liveScheduleUseCase := usecase.NewLiveScheduleUseCase(liveScheduleRepository, waitRoomHub, hub, v2, logger)
	handler := delivery.NewHandler(authUseCase, userUseCase, storyUseCase, commentUseCase, likeUseCase, messageUseCase, privateChatUsecase, paidInteractionUsecase, bookingUsecase, offerUsecase, locationUsecase, liveScheduleUseCase, waitRoomHub, hub, logger)
	roomManager := webrtc.NewRoomManager(logger)
	streamRepository := repository.NewStreamRepository(pool, logger)
	streamSessionRepository := repository.NewStreamSessionRepository(pool, logger)
	streamUseCase := usecase.NewStreamUseCase(streamRepository, streamSessionRepository, walletRepository, client, broker, logger)
	trendingUseCase := usecase.NewTrendingUseCase(pool, client, streamRepository, logger)
	webRTCHandler := delivery.NewWebRTCHandler(roomManager, streamUseCase, authUseCase, trendingUseCase, liveScheduleUseCase, logger)
	vodMediaRepository := repository.NewVODMediaRepository(pool, logger)
	drmRepository := repository.NewDRMRepository(pool, logger)
	fFmpeg := FFmpegProvider(logger)
	storage := StorageProvider(logger)
	workerPool := WorkerPoolProvider(logger)
	vodUseCase := usecase.NewVODUseCase(vodMediaRepository, drmRepository, fFmpeg, storage, client, workerPool, logger)
	vodUseCaseInterface := VODUseCaseProvider(vodUseCase)
	vodHandler := delivery.NewVODHandler(vodUseCaseInterface, logger)
	walletUseCase := usecase.NewWalletUseCase(walletRepository, transactionRepository, client, logger)
	giftRepository := repository.NewGiftRepository(pool, logger)
	giftTransactionRepository := repository.NewGiftTransactionRepository(pool, logger)
	giftUseCase := usecase.NewGiftUseCase(giftRepository, giftTransactionRepository, agencyRepository, walletUseCase, privateChatUsecase, messageRepository, chatRoomRepository, hub, client, logger)
	hostApplicationRepository := repository.NewHostApplicationRepository(pool, logger)
	agencyUseCase := usecase.NewAgencyUseCase(hostApplicationRepository, agencyRepository, walletUseCase, logger)
	duitkuPaymentRepository := repository.NewDuitkuPaymentRepository(pool, logger)
	duitkuClient := DuitkuClientProvider(config, logger)
	paymentUseCase := usecase.NewPaymentUseCase(transactionRepository, duitkuPaymentRepository, walletUseCase, duitkuClient, client, logger)
	monetizationHandler := delivery.NewMonetizationHandler(walletUseCase, giftUseCase, agencyUseCase, paymentUseCase, withdrawalUsecase, logger)
	monetizationRepository := repository.NewMonetizationRepository(pool, logger)
	monetizationUseCase := usecase.NewMonetizationUseCase(monetizationRepository, walletRepository, transactionRepository, streamRepository, logger)
	extraMonetizationHandler := delivery.NewExtraMonetizationHandler(monetizationUseCase, logger)
	v3 := PublisherProvider(broker)
	healthHandler := delivery.NewHealthHandler(pool, client, v3)
	cryptoRepository := repository.NewCryptoRepository(pool, logger)
	string2 := CryptoMasterMnemonicProvider(config)
	cryptoUseCase := usecase.NewCryptoUseCase(cryptoRepository, walletUseCase, client, logger, v, string2)
	cryptoMonitor := CryptoMonitorProvider(cryptoRepository, cryptoUseCase, config, logger)
	cryptoHandler := delivery.NewCryptoHandler(cryptoUseCase, cryptoMonitor, logger)
	pkBattleRepository := repository.NewPKBattleRepository(pool, logger)
	pkBattleUseCase := usecase.NewPKBattleUseCase(pkBattleRepository, streamRepository, hub, client, logger)
	pkBattleHandler := delivery.NewPKBattleHandler(pkBattleUseCase, logger)
	moderationRepository := repository.NewModerationRepository(pool, logger)
	nsfwScanner := usecase.NewAWSRekognitionScanner(logger)
	moderationUseCase := usecase.NewModerationUseCase(moderationRepository, hub, client, logger, nsfwScanner)
	moderationHandler := delivery.NewModerationHandler(moderationUseCase, logger)
	creatorTokenRepository := repository.NewCreatorTokenRepository(pool, logger)
	creatorTokenUseCaseInterface := usecase.NewCreatorTokenUseCase(creatorTokenRepository, walletRepository, transactionRepository, logger)
	creatorTokenHandler := delivery.NewCreatorTokenHandler(creatorTokenUseCaseInterface, logger)
	predictionRepository := repository.NewPredictionRepository(pool, logger)
	predictionUseCaseInterface := usecase.NewPredictionUseCase(predictionRepository, streamRepository, walletRepository, transactionRepository, creatorTokenRepository, logger)
	predictionHandler := delivery.NewPredictionHandler(predictionUseCaseInterface, logger)
	drmUseCaseInterface := usecase.NewDRMUseCase(drmRepository, vodMediaRepository, logger)
	drmHandler := delivery.NewDRMHandler(drmUseCaseInterface, vodUseCaseInterface, logger)
	recommendationRepository := repository.NewRecommendationRepository(pool, logger)
	recommendationUseCaseInterface := usecase.NewRecommendationUseCase(recommendationRepository, streamRepository, vodMediaRepository, logger)
	recommendationHandler := delivery.NewRecommendationHandler(recommendationUseCaseInterface, logger)
	clipRepository := repository.NewClipRepository(pool, logger)
	clipUseCaseInterface := usecase.NewClipUseCase(clipRepository, streamRepository, client, logger)
	clipHandler := delivery.NewClipHandler(clipUseCaseInterface, logger)
	kycRepository := repository.NewKYCRepository(pool, logger)
	bannedUserRepository := repository.NewBannedUserRepository(pool, logger)
	onboardingRepository := repository.NewOnboardingRepository(pool, logger)
	kycUseCase := usecase.NewKYCUseCase(kycRepository, userRepository, bannedUserRepository, streamRepository, onboardingRepository, logger)
	onboardingUseCase := usecase.NewOnboardingUseCase(onboardingRepository, userRepository, logger)
	kycHandler := delivery.NewKYCHandler(kycUseCase, onboardingUseCase, logger)
	clipSubscriptionRepository := repository.NewClipSubscriptionRepository(pool, logger)
	clipSubscriptionUseCase := usecase.NewClipSubscriptionUseCase(clipSubscriptionRepository, userRepository, walletUseCase, logger)
	clipSubscriptionHandler := delivery.NewClipSubscriptionHandler(clipSubscriptionUseCase, logger)
	dashboardRepository := repository.NewDashboardRepository(pool, logger)
	dashboardUseCase := usecase.NewDashboardUseCase(dashboardRepository, userRepository, bannedUserRepository, streamRepository, commentRepository, kycRepository, agencyRepository, logger)
	dashboardHandler := delivery.NewDashboardHandler(dashboardUseCase, logger)
	payoutHandler := delivery.NewPayoutHandler(payoutUsecase, logger)
	pushSubscriptionRepository := repository.NewPushSubscriptionRepository(pool, logger)
	pushNotificationUsecase := PushNotificationUseCaseProvider(pushSubscriptionRepository, config, logger)
	pushHandler := delivery.NewPushHandler(pushNotificationUsecase, logger)
	vipRepository := repository.NewVIPRepository(pool, logger)
	vipUseCase := usecase.NewVIPUseCase(vipRepository, walletRepository, transactionRepository, client, logger)
	vipHandler := delivery.NewVIPHandler(vipUseCase)
	royalFamilyRepository := repository.NewRoyalFamilyRepository(pool, logger)
	royalFamilyUseCase := usecase.NewRoyalFamilyUseCase(royalFamilyRepository, walletRepository, transactionRepository, client, logger)
	royalFamilyHandler := delivery.NewRoyalFamilyHandler(royalFamilyUseCase)
	shortVideoRepository := repository.NewShortVideoRepository(pool, logger)
	streamTagRepository := repository.NewStreamTagRepository(pool, logger)
	shortVideoUseCase := usecase.NewShortVideoUseCase(shortVideoRepository, streamTagRepository, client, logger)
	shortVideoHandler := delivery.NewShortVideoHandler(shortVideoUseCase)
	inventoryRepository := repository.NewInventoryRepository(pool, logger)
	inventoryUseCase := usecase.NewInventoryUseCase(inventoryRepository, logger)
	inventoryHandler := delivery.NewInventoryHandler(inventoryUseCase)
	wheelRepository := repository.NewWheelRepository(pool, logger)
	wheelUseCase := usecase.NewWheelUseCase(wheelRepository, walletRepository, inventoryRepository, transactionRepository, client, logger)
	wheelHandler := delivery.NewWheelHandler(wheelUseCase)
	missionRepository := repository.NewMissionRepository(pool, logger)
	missionUseCase := usecase.NewMissionUseCase(missionRepository, walletRepository, logger)
	missionHandler := delivery.NewMissionHandler(missionUseCase)
	voiceRoomRepository := repository.NewVoiceRoomRepository(pool, logger)
	voiceRoomUseCase := usecase.NewVoiceRoomUseCase(voiceRoomRepository, logger)
	voiceRoomHandler := delivery.NewVoiceRoomHandler(voiceRoomUseCase)
	luckyBagRepository := repository.NewLuckyBagRepository(pool, logger)
	luckyBagUseCase := usecase.NewLuckyBagUseCase(luckyBagRepository, walletRepository, client, logger)
	luckyBagHandler := delivery.NewLuckyBagHandler(luckyBagUseCase)
	hostLevelRepository := repository.NewHostLevelRepository(pool, logger)
	hostLevelUseCase := usecase.NewHostLevelUseCase(hostLevelRepository, userRepository, logger)
	hostLevelHandler := delivery.NewHostLevelHandler(hostLevelUseCase)
	authMiddleware := middleware.NewAuthMiddleware(service, client, logger)
	rbacMiddleware := middleware.NewRBACMiddleware(manager, logger)
	rateLimitMiddleware := RateLimitMiddlewareProvider(client, logger, config)
	idempotencyManager := wallet.NewIdempotencyManager(client, logger)
	banChecker := middleware.NewBanChecker(bannedUserRepository, logger)
	clipQuotaMiddleware := middleware.NewClipQuotaMiddleware(clipSubscriptionUseCase, logger)
	router := delivery.SetupRouter(handler, webRTCHandler, vodHandler, monetizationHandler, extraMonetizationHandler, healthHandler, cryptoHandler, pkBattleHandler, moderationHandler, creatorTokenHandler, predictionHandler, drmHandler, recommendationHandler, clipHandler, kycHandler, clipSubscriptionHandler, dashboardHandler, payoutHandler, pushHandler, vipHandler, royalFamilyHandler, shortVideoHandler, inventoryHandler, wheelHandler, missionHandler, voiceRoomHandler, luckyBagHandler, hostLevelHandler, authMiddleware, rbacMiddleware, rateLimitMiddleware, idempotencyManager, banChecker, clipQuotaMiddleware, logger)
	levelingUseCase := usecase.NewLevelingUseCase(pool, client, hub, logger)
	appContainer := &AppContainer{
		Config:             config,
		DB:                 db,
		Redis:              client,
		Logger:             logger,
		Router:             router,
		WaitRoomHub:        waitRoomHub,
		WSHub:              hub,
		ModerationUseCase:  moderationUseCase,
		ScheduleUseCase:    liveScheduleUseCase,
		PrivateChatUseCase: privateChatUsecase,
		StreamUseCase:      streamUseCase,
		VIPUseCase:         vipUseCase,
		HostLevelUseCase:   hostLevelUseCase,
		CryptoUseCase:      cryptoUseCase,
		CryptoRepo:         cryptoRepository,
		CryptoMonitor:      cryptoMonitor,
		WorkerPool:         workerPool,
		TrendingUseCase:    trendingUseCase,
		VODUseCase:         vodUseCase,
		LevelingUseCase:    levelingUseCase,
		WebRTCRoomManager:  roomManager,
		RBACManager:        manager,
		RoleRepo:           roleRepository,
	}
	return appContainer, nil
}

// wire.go:

// AppContainer holds the initialized core dependencies for the server.
type AppContainer struct {
	Config             *config.Config
	DB                 *database.DB
	Redis              *redis.Client
	Logger             *zap.Logger
	Router             *mux.Router
	WaitRoomHub        *websocket.WaitRoomHub
	WSHub              *websocket.Hub
	ModerationUseCase  domain.ModerationUseCase
	ScheduleUseCase    domain.LiveScheduleUseCase
	PrivateChatUseCase domain.PrivateChatUsecase
	StreamUseCase      *usecase.StreamUseCase
	VIPUseCase         *usecase.VIPUseCase
	HostLevelUseCase   *usecase.HostLevelUseCase
	CryptoUseCase      *usecase.CryptoUseCase
	CryptoRepo         domain.CryptoRepository
	CryptoMonitor      *worker.CryptoMonitor
	WorkerPool         *worker2.WorkerPool
	TrendingUseCase    *usecase.TrendingUseCase
	VODUseCase         *usecase.VODUseCase
	LevelingUseCase    *usecase.LevelingUseCase
	WebRTCRoomManager  *webrtc.RoomManager
	RBACManager        *rbac.Manager
	RoleRepo           domain.RoleRepository
}
